name: classlink_resources
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  url_launcher: ^6.1.10
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^4.0.3
  csv: ^5.0.1
  get_storage: ^2.1.1
  google_sign_in: ^6.1.0
  firebase_core: ^2.10.0
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_adaptive_ui: ^0.8.0+1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_launcher_icons:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  # add assets
  assets: 
    - assets/data/
    - assets/icons/

flutter_icons:
  image_path: "assets/icons/favicon.png"
  web:
    generate: true
    image_path: "assets/icons/favicon.png"
